name: LD-Fitness-0863
channels:
  - conda-forge
  - defaults
dependencies:
  - anaconda=custom
  - attrs=19.1.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - bzip2=1.0.6
  - ca-certificates=2018.11.29
  - certifi=2018.11.29
  - decorator=4.3.2
  - defusedxml=0.5.0
  - entrypoints=0.3
  - freetype=2.9.1
  - icu=58.2
  - intel-openmp=2019.1
  - ipykernel=5.1.0
  - ipython=7.3.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - jedi=0.13.3
  - jinja2=2.10
  - jpeg=9c
  - jsonschema=3.0.1
  - jupyter=1.0.0
  - jupyter_client=5.2.4
  - jupyter_console=6.0.0
  - jupyter_core=4.4.0
  - kiwisolver=1.0.1
  - libffi=3.2.1
  - libpng=1.6.36
  - libsodium=1.0.16
  - llvm-meta=7.0.0
  - markupsafe=1.1.1
  - matplotlib=3.0.3
  - matplotlib-base=3.0.3
  - mistune=0.8.4
  - mkl=2019.1
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - nbconvert=5.4.1
  - nbformat=4.4.0
  - ncurses=6.1
  - notebook=5.7.5
  - numpy=1.16.2
  - numpy-base=1.16.2
  - openssl=1.0
  - pandas=0.24.1
  - pandoc=2.6
  - pandocfilters=1.4.2
  - parso=0.3.4
  - patsy=0.5.1
  - pexpect=4.6.0
  - pickleshare=0.7.5
  - pip=19.0.3
  - prometheus_client=0.6.0
  - prompt_toolkit=2.0.9
  - ptyprocess=0.6.0
  - pygments=2.3.1
  - pyparsing=2.3.1
  - pyqt=5.6.0
  - pyrsistent=0.14.11
  - python=3.7.1
  - python-dateutil=2.8.0
  - pytz=2018.9
  - pyzmq=18.0.1
  - qt=5.6.2
  - qtconsole=4.4.3
  - readline=7.0
  - scipy=1.2.1
  - send2trash=1.5.0
  - setuptools=40.8.0
  - sip=4.18.1
  - six=1.12.0
  - sqlite=3.26.0
  - statsmodels=0.9.0
  - terminado=0.8.1
  - testpath=0.4.2
  - tk=8.6.9
  - tornado=6.0.1
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.1
  - widgetsnbextension=3.4.2
  - xz=5.2.4
  - zeromq=4.2.5
  - zlib=1.2.11
  - pip:
    - cycler==0.10.0
    - seaborn==0.9.0
prefix: /Users/davidwelkie/anaconda3/envs/LD-Fitness-0863

